
spring.application.name=karaoke-backend


server.port=8080


# Gi?i h?n dung l??ng cho 1 file (Ví d?: 500 Megabytes)
spring.servlet.multipart.max-file-size=500MB

# Gi?i h?n dung l??ng cho toàn b? form upload cùng lúc
spring.servlet.multipart.max-request-size=500MB
spring.h2.console.enabled=true



