
spring.application.name=karaoke-backend


server.port=8080

spring.servlet.multipart.max-file-size=500MB

spring.servlet.multipart.max-request-size=500MB
spring.h2.console.enabled=true

cloudinary.cloud-name=dvw8sbpez
cloudinary.api-key=228352252691355
cloudinary.api-secret=nLUluIgKV-QQl-nBEcc-Y2GxBcE



