package com.karaoke.backend.model;

public enum GameState {
JOIN,LOBBY, PLAY_SEGMENT, BATTLE, WINNER_SHOW, COUNTDOWN, PERFORMANCE, VOTE, CHAT, PAUSE, SCORE_SHOW, KICK_PLAYER, END_GAME, TOGGLE_READY
}
