package com.karaoke.backend.model;

public enum GameState {
    JOIN, LOBBY, PLAY_SEGMENT, BATTLE, WINNER_SHOW, COUNTDOWN, PERFORMANCE, PERFORMANCE_EVALUATION, CHAT, PAUSE, SCORE_SHOW, KICK_PLAYER,
    END_GAME, TOGGLE_READY, VOICE, RTC_SIGNAL, USER_LYRICS
}
